### ISSUE TITLE
Dialog examples announce skip nav and main landmark on close in Firefox

### ISSUE THREAD

**Issue by poorgeek** [scottaohara/accessible_modal_window#5]
I noticed that when I close any of the modal dialogs on the [example page](http://scottaohara.github.io/accessible_modal_window/) that I get some odd announcements from Firefox 52 (ESR). 

* NVDA 2018.1 announces the Skip link and the main content landmark before announcing the button that receives focus after close. 
* Jaws 2018 announces the main content landmark followed by the button.

**Comment by scottaohara** [comment]
This is odd...

Never noticed this in previous testing, and testing a few other modal scripts, I'm noticing the same sort of issue.  Also happens in Chrome.  I'm wondering if this is a weird NVDA quirk?  Will look at it more.

**Comment by scottaohara** [comment]
This definitely seems to be an NVDA issue rather than an issue, and how it announces content when it's re-exposed to the a11y tree.

If using `aria-modal` instead of hiding content with `aria-hidden='true'`, the issue doesn't exist.  But since `aria-modal` doesn't 100% hide content from NVDA (tested with 2018.1), in corner cases where a user navigates to the address bar, and then tabs back into the document, with a dialog open, these extra announcements may be better than the alternative.

Closing for now since it's an AT issue.
